import Navbar from "../components/Navbar";

function Reports() {

  const downloadReport = (
    title,
    plagiarism,
    originality
  ) => {

    const reportContent = `
Plagiarism Checker Report

Title: ${title}

Plagiarism Score: ${plagiarism}%
Originality Score: ${originality}%

Generated by Plagiarism Checker
`;

    const blob = new Blob(
      [reportContent],
      {
        type: "text/plain",
      }
    );

    const link =
      document.createElement("a");

    link.href =
      URL.createObjectURL(blob);

    link.download =
      `${title}.txt`;

    link.click();
  };

  return (
    <div className="dashboard-page">
      <Navbar />

      <div className="dashboard-container">

        <h1>Reports 📄</h1>

        <p>
          View plagiarism analysis
          reports and history.
        </p>

        <div className="report-card">
          <h3>FED Project Report</h3>

          <p>
            Plagiarism Score: 0%
          </p>

          <p>
            Originality: 100%
          </p>

          <button
            className="download-btn"
            onClick={() =>
              downloadReport(
                "FED Project Report",
                0,
                100
              )
            }
          >
            Download Report
          </button>
        </div>

        <div className="report-card">
          <h3>Research Paper</h3>

          <p>
            Plagiarism Score: 75%
          </p>

          <p>
            Originality: 25%
          </p>

          <button
            className="download-btn"
            onClick={() =>
              downloadReport(
                "Research Paper",
                75,
                25
              )
            }
          >
            Download Report
          </button>
        </div>

      </div>
    </div>
  );
}

export default Reports;